//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Berlet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Berlet()
        {
            this.Belepes = new HashSet<Belepe>();
            this.Vasarolts = new HashSet<Vasarolt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Idotartam { get; set; }
        public Nullable<int> Belepesek_szama { get; set; }
        public Nullable<int> Kezdeti_ora { get; set; }
        public Nullable<int> Veg_ora { get; set; }
        public byte[] Napok { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Belepe> Belepes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vasarolt> Vasarolts { get; set; }
    }
}
