//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ertek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ertek()
        {
            this.Vasarolts = new HashSet<Vasarolt>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Mikortol { get; set; }
        public Nullable<System.DateTime> Meddig { get; set; }
        public Nullable<decimal> Ar { get; set; }
        public Nullable<int> Tipus { get; set; }
    
        public virtual Tipu Tipu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vasarolt> Vasarolts { get; set; }
    }
}
