//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitneszDBContext : DbContext
    {
        public FitneszDBContext()
            : base("name=FitneszDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Belepe> Belepes { get; set; }
        public virtual DbSet<Berlet> Berlets { get; set; }
        public virtual DbSet<Ertek> Erteks { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Tipu> Tipus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vasarolt> Vasarolts { get; set; }
    }
}
